http://localhost:5000/api/usuarios/

###
POST http://localhost:5000/api/usuarios/
Content-Type: application/json

{
  "nombre":"Miguel Angel"
}

###
PUT http://localhost:5000/api/usuarios/4
Content-Type: application/json

{
  "nombre":"Natalia"
}

###
DELETE http://localhost:5000/api/usuarios/3 HTTP/1.1
